// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../../../routes/profile/[profileId]/collections/[collectionId].dart';

abstract class CollectionsCollectionIdPageRoute extends AppRoute {
  CollectionsCollectionIdPageRoute({
    required this.profileId,
    required this.collectionId,
  });

  final String profileId;
  final String collectionId;

  Uri toUri() => Uri.parse('/profile/$profileId/collections/$collectionId');

  List<Object?> get props => [profileId, collectionId];
}
