// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../../routes/tabs/feed/_layout.dart';

abstract class FeedIndexedTabLayout extends AppRoute with RouteLayout<AppRoute> {
  FeedIndexedTabLayout();

  @override
  IndexedStackPath<AppRoute> resolvePath(
    covariant AppCoordinator coordinator,
  ) => coordinator.tabsFeedPath;
}
