// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../routes/tabs/_layout.dart';

abstract class TabsLayout extends AppRoute with RouteLayout<AppRoute> {
  TabsLayout();

  @override
  IndexedStackPath<AppRoute> resolvePath(
    covariant AppCoordinator coordinator,
  ) => coordinator.tabsPath;
}
