// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../routes/tabs/profile.dart';

abstract class ProfileTabRoute extends AppRoute {
  ProfileTabRoute();

  Uri toUri() => Uri.parse('/tabs/profile');

  List<Object?> get props => [];
}
