// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../routes/tabs/settings.dart';

abstract class SettingsTabRoute extends AppRoute {
  SettingsTabRoute();

  Uri toUri() => Uri.parse('/tabs/settings');

  List<Object?> get props => [];
}
