// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../routes/profile/general.dart';

abstract class GeneralPageRoute extends AppRoute {
  GeneralPageRoute();

  Uri toUri() => Uri.parse('/profile/general');

  List<Object?> get props => [];
}
