// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../../routes/profile/[profileId]/index.dart';

abstract class ProfilePageRoute extends AppRoute {
  ProfilePageRoute({
    required this.profileId,
  });

  final String profileId;

  Uri toUri() => Uri.parse('/profile/$profileId');

  List<Object?> get props => [profileId];
}
