// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../../../routes/tabs/feed/for-you/_layout.dart';

abstract class ForYouStackedLayout extends AppRoute with RouteLayout<AppRoute> {
  ForYouStackedLayout();

  @override
  NavigationPath<AppRoute> resolvePath(
    covariant AppCoordinator coordinator,
  ) => coordinator.tabsFeedForYouPath;
}
