// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../../../../routes/tabs/feed/for-you/index.dart';

abstract class ForYouRoute extends AppRoute {
  ForYouRoute();

  Uri toUri() => Uri.parse('/tabs/feed/for-you');

  List<Object?> get props => [];
}
