// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../routes/about.dart';

abstract class AboutPageRoute extends AppRoute {
  AboutPageRoute();

  Uri toUri() => Uri.parse('/about');

  List<Object?> get props => [];
}
