// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of '../../routes/index.dart';

abstract class IndexPageRoute extends AppRoute {
  IndexPageRoute();

  Uri toUri() => Uri.parse('/');

  List<Object?> get props => [];
}
